version: '3.7'
services:
  flok:
    build: 
      context: .
      dockerfile: Dockerfile
    image: yassinsiouda/flok-server:next
    container_name: flok-server
    
    ports:
      - 4500:3000
    env_file:
      - .env
  
