name: Build flok server

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and push flok server Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t yassinsiouda/flok-server:latest .
          docker images

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: yassinsiouda/flok-server:latest
